apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myplat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Public repo => ArgoCD pulls it credential-less (same as the flask-app demo).
    repoURL: https://github.com/karimkhaled842/myplat
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: myplat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
